import { Project } from "@/types/project";

// Плейсхолдеры — замени cover/images на свои работы (см. /public/images/work),
// заполни title/description на трёх языках. slug используется в адресе
// страницы проекта: /work/<slug> — сделай его коротким и на латинице.
export const projects: Project[] = [
  {
    id: "1",
    slug: "socurdmitrii_logo",
    title: { ru: "Логотип для дизайнера Socur Dmitrii",
            en: "Logo for designer Socur Dmitrii",
            ro: "Logo pentru designerul Socur Dmitrii" },
    categoryKey: "branding",

    year: 2026,
    cover: "/images/work/logo/socurdmitrii/cover-1.jpg",
    images: [
      "/images/work/logo/socurdmitrii/work.jpg",
      "/images/work/logo/socurdmitrii/work3.png",
      "/images/work/logo/socurdmitrii/work4.png",
      "/images/work/logo/socurdmitrii/work5.jpg",
      "/images/work/logo/socurdmitrii/work6.jpg",
      "/images/work/logo/socurdmitrii/work8.png",
      "/images/work/logo/socurdmitrii/work7.jpg",
      "/images/work/logo/socurdmitrii/work9.jpg"],
    description: {
      ru: "Логотип, разработанный для себя. Лого выполнено в плоском стиле, сочетает в себе аббревиатуру имени и фамилии Socur Dmitrii. Помимо этого, для формирования визуального баланса левая часть была дополнена вертикальным элементом, который замыкает фигуру.",
      en: "A logo I designed for myself. The logo is created in a flat style and combines the initials of my first and last name, Socur Dmitrii. In addition, to create visual balance, a vertical element was added to the left side to complete the shape.",
      ro: "Un logo creat pentru mine. Logo-ul este realizat în stil plat și combină inițialele numelui și prenumelui Socur Dmitrii. În plus, pentru a crea un echilibru vizual, partea stângă a fost completată cu un element vertical care încheie forma.",
    },
  },
  {
    id: "2",
    slug: "energywind_prezentation",
    title: { ru: "Презентация компании System Global Group в области ветроэнергетики (Energy Wind Moldova)",
            en: "System Global Group's Presentation on Wind Energy (Energy Wind Moldova)",
            ro: "Prezentarea companiei System Global Group în domeniul energiei eoliene (Energy Wind Moldova)" },
    categoryKey: "web",
    year: 2026,
    cover: "/images/work/web/energy_prezentation/cover-2.jpg",
    images: [
  "/images/work/web/energy_prezentation/лист 1 копия.jpg",
  "/images/work/web/energy_prezentation/лист 2 копия.jpg",
  "/images/work/web/energy_prezentation/лист 3 копия.jpg",
  "/images/work/web/energy_prezentation/лист 4 копия.jpg",
  "/images/work/web/energy_prezentation/лист 5 копия.jpg",
  "/images/work/web/energy_prezentation/лист 6 копия.jpg",
  "/images/work/web/energy_prezentation/лист 7 копия.jpg",
  "/images/work/web/energy_prezentation/лист 8 копия.jpg",
  "/images/work/web/energy_prezentation/лист 9 копия.jpg",
  "/images/work/web/energy_prezentation/лист 10 копия.jpg",
  "/images/work/web/energy_prezentation/лист 11 копия.jpg",
  "/images/work/web/energy_prezentation/лист 12 копия.jpg",
  "/images/work/web/energy_prezentation/лист 13 копия.jpg",
  "/images/work/web/energy_prezentation/лист 14 копия.jpg",
  "/images/work/web/energy_prezentation/лист 15 копия.jpg",
  "/images/work/web/energy_prezentation/лист 16 копия.jpg",
  "/images/work/web/energy_prezentation/лист 17 копия.jpg",
  "/images/work/web/energy_prezentation/лист 18 копия.jpg",
  "/images/work/web/energy_prezentation/лист 19 копия.jpg",
  "/images/work/web/energy_prezentation/лист 20 копия.jpg"
],

    description: {
      ru: "Презентация для компании Energy Wind Moldova в области ветроэнергетики показывает, чем занимается клиент: строительство ветряных электростанций и систем накопления энергии, их монтаж, сервисное обслуживание и финансирование проектов. В документе отражены ключевые направления — надёжность оборудования, технологическая экспертиза, доступные финансовые инструменты (лизинг, рассрочка), а также вклад компании в устойчивое развитие и экологичность решений.",
      en: "This presentation for Energy Wind Moldova, a company in the wind energy sector, outlines the client’s core activities: the construction of wind power plants and energy storage systems, their installation, maintenance, and project financing. The document highlights key areas—equipment reliability, technical expertise, accessible financial instruments (leasing, installment plans), as well as the company’s contribution to sustainable development and environmentally friendly solutions.",
      ro: "Prezentarea pentru compania Energy Wind Moldova din domeniul energiei eoliene ilustrează activitatea clientului: construcția de centrale eoliene și sisteme de stocare a energiei, instalarea acestora, întreținerea și finanțarea proiectelor. Documentul evidențiază direcțiile cheie — fiabilitatea echipamentelor, expertiza tehnologică, instrumentele financiare accesibile (leasing, rate), precum și contribuția companiei la dezvoltarea durabilă și la caracterul ecologic al soluțiilor.",
    },
  },
  {
    id: "3",
    slug: "project-three",
    title: { ru: "Название проекта", en: "Project name", ro: "Numele proiectului" },
    categoryKey: "print",
    year: 2025,
    cover: "/images/work/cover-3.svg",
    images: ["/images/work/cover-3.svg", "/images/work/detail-1.svg", "/images/work/detail-2.svg"],
    description: {
      ru: "Краткое описание проекта: расскажи, что сделал в этой работе. Замени этот текст на реальную историю.",
      en: "Short project description: tell the story of what you did in this piece of work. Replace this with the real text.",
      ro: "Descriere scurtă a proiectului: povestește ce ai făcut în acest proiect. Înlocuiește cu textul real.",
    },
  },
  {
    id: "4",
    slug: "project-four",
    title: { ru: "Название проекта", en: "Project name", ro: "Numele proiectului" },
    categoryKey: "packaging",
    year: 2025,
    cover: "/images/work/cover-4.svg",
    images: ["/images/work/cover-4.svg", "/images/work/detail-1.svg", "/images/work/detail-2.svg"],
    description: {
      ru: "Краткое описание проекта: расскажи, что сделал в этой работе. Замени этот текст на реальную историю.",
      en: "Short project description: tell the story of what you did in this piece of work. Replace this with the real text.",
      ro: "Descriere scurtă a proiectului: povestește ce ai făcut în acest proiect. Înlocuiește cu textul real.",
    },
  },
  {
    id: "5",
    slug: "project-five",
    title: { ru: "Название проекта", en: "Project name", ro: "Numele proiectului" },
    categoryKey: "video-editing",
    year: 2025,
    cover: "/images/work/cover-5.svg",
    images: ["/images/work/cover-5.svg", "/images/work/detail-1.svg", "/images/work/detail-2.svg"],
    description: {
      ru: "Краткое описание проекта: расскажи, что сделал в этой работе. Замени этот текст на реальную историю.",
      en: "Short project description: tell the story of what you did in this piece of work. Replace this with the real text.",
      ro: "Descriere scurtă a proiectului: povestește ce ai făcut în acest proiect. Înlocuiește cu textul real.",
    },
  },
  {
    id: "6",
    slug: "project-six",
    title: { ru: "Название проекта", en: "Project name", ro: "Numele proiectului" },
    categoryKey: "Motion design",
    year: 2024,
    cover: "/images/work/cover-6.svg",
    images: ["/images/work/cover-6.svg", "/images/work/detail-1.svg", "/images/work/detail-2.svg"],
    description: {
      ru: "Логотип созданный в рамках лицензионного проекта (Исследование и разработка визуальной идентичности Факультета ȘREM, USARB: от концепции до реализации), с последующем применением. В основе логотипа лежит аббревиатура слов Matematica/Informatica, вписанные в увадратные скобки, которые используются в обеих дисциплинах.",
      en: "Short project description: tell the story of what you did in this piece of work. Replace this with the real text.",
      ro: "Descriere scurtă a proiectului: povestește ce ai făcut în acest proiect. Înlocuiește cu textul real.",
    },
  },
  {
    id: "7",
    slug: "catedra_matinf_logo",
    title: { ru: "Логотип для кафедры математики и информатики факультета ȘREM, USARB", en: "Logo for the Department of Mathematics and Computer Science, ȘREM Faculty, USARB", ro: "Logotip pentru catedra de matematică și informatică a facultății ȘREM, USARB" },
    categoryKey: "branding",
    year: 2026,
    cover: "/images/work/logo/matematica/cover-7.jpg",
    images: [
      "/images/work/logo/matematica/work1.jpg",
      "/images/work/logo/matematica/work2.jpg",
      "/images/work/logo/matematica/work3.png",
      "/images/work/logo/matematica/work4.jpg",
      "/images/work/logo/matematica/work5.jpg",
      "/images/work/logo/matematica/work6.jpg",
      "/images/work/logo/matematica/work7.jpg",
      "/images/work/logo/matematica/work8.jpg"
            ],
    description: {
      ru: "Логотип, созданный в рамках лицензионного проекта («Исследование и разработка визуальной идентичности факультета ȘREM, USARB: от концепции до реализации»), с последующим применением. В основе логотипа лежит аббревиатура слов Matematica/Informatica, вписанных в квадратные скобки, которые используются в обеих дисциплинах.",
      en: "A logo created as part of a licensing project (“Research and Development of the Visual Identity for the ȘREM Faculty, USARB: From Concept to Implementation”), followed by its implementation. The logo is based on the abbreviation of the words “Matematica/Informatica,” enclosed in square brackets, which are used in both disciplines.",
      ro: "Logo-ul creat în cadrul proiectului licențial („Cercetarea și dezvoltarea identității vizuale a Facultății ȘREM, USARB: de la concept la realizare”), urmat de punerea sa în practică. La baza logo-ului stă abrevierea cuvintelor „Matematica/Informatica”, încadrate între paranteze pătrate, care sunt utilizate în ambele discipline.",
    },
  },
  {
    id: "8",
    slug: "project-eight",
    title: { ru: "Название проекта", en: "Project name", ro: "Numele proiectului" },
    categoryKey: "web",
    year: 2024,
    cover: "/images/work/cover-8.svg",
    images: ["/images/work/cover-8.svg", "/images/work/detail-1.svg", "/images/work/detail-2.svg"],
    description: {
      ru: "Краткое описание проекта: расскажи, что сделал в этой работе. Замени этот текст на реальную историю.",
      en: "Short project description: tell the story of what you did in this piece of work. Replace this with the real text.",
      ro: "Descriere scurtă a proiectului: povestește ce ai făcut în acest proiect. Înlocuiește cu textul real.",
    },
  },
  {
    id: "9",
    slug: "project-nine",
    title: { ru: "Название проекта", en: "Project name", ro: "Numele proiectului" },
    categoryKey: "print",
    year: 2023,
    cover: "/images/work/cover-9.svg",
    images: ["/images/work/cover-9.svg", "/images/work/detail-1.svg", "/images/work/detail-2.svg"],
    description: {
      ru: "Краткое описание проекта: расскажи, что сделал в этой работе. Замени этот текст на реальную историю.",
      en: "Short project description: tell the story of what you did in this piece of work. Replace this with the real text.",
      ro: "Descriere scurtă a proiectului: povestește ce ai făcut în acest proiect. Înlocuiește cu textul real.",
    },
  },
  {
    id: "10",
    slug: "project-ten",
    title: { ru: "Название проекта", en: "Project name", ro: "Numele proiectului" },
    categoryKey: "print",
    year: 2023,
    cover: "/images/work/cover-10.svg",
    images: ["/images/work/cover-10.svg", "/images/work/detail-1.svg", "/images/work/detail-2.svg"],
    description: {
      ru: "Краткое описание проекта: расскажи, что сделал в этой работе. Замени этот текст на реальную историю.",
      en: "Short project description: tell the story of what you did in this piece of work. Replace this with the real text.",
      ro: "Descriere scurtă a proiectului: povestește ce ai făcut în acest proiect. Înlocuiește cu textul real.",
    },
  },
  {
    id: "11",
    slug: "energywind_logo",
    title: { ru: "Логотип для компании в области ветроэнергетики System Global Group (Energy Wind Moldova)",
            en: "Logo for System Global Group (Energy Wind Moldova), a company in the wind energy sector",
            ro: "Logo pentru compania din domeniul energiei eoliene System Global Group (Energy Wind Moldova)" },
    categoryKey: "branding",
    year: 2026,
    cover: "/images/work/logo/energywind/cover-11.jpg",
    images: [
      "/images/work/logo/energywind/work1.jpg",
      "/images/work/logo/energywind/work2.jpg",
      "/images/work/logo/energywind/work3.jpg",
      "/images/work/logo/energywind/work4.jpg",
      "/images/work/logo/energywind/work5.jpg",
      "/images/work/logo/energywind/work6.jpg",
      "/images/work/logo/energywind/work9.jpg",
      "/images/work/logo/energywind/work7.jpg",
      "/images/work/logo/energywind/work8.jpg"
            ],
    description: {
      ru: "Логотип, созданный для компании, которая занимается ветроэнергетикой в Молдове — Energy Wind Moldova. Логотип выполнен в современном стиле с использованием зелёных оттенков, отражающих экологичность и возобновляемую энергию.",
      en: "A logo created for a company specializing in wind energy in Moldova — Energy Wind Moldova. The logo is designed in a modern style using green shades that reflect environmental friendliness and renewable energy.",
      ro: "Logo-ul creat pentru o companie care se ocupă de energie eoliană în Moldova — Energy Wind Moldova. Logo-ul este realizat într-un stil modern folosind nuanțe de verde care reflectă prietenia față de mediu și energia regenerabilă.",
    },
  },
  {
    id: "12",
    slug: "HDL_logo",
    title: { ru: "Логотип для киберспортивной команды HDL (Hope Dies Last)",
            en: "Logo for the HDL (Hope Dies Last) esports team",
            ro: "Logo pentru echipa de e-sport HDL (Hope Dies Last)" },
    categoryKey: "branding",
    year: 2026,
    cover: "/images/work/logo/hdl/cover-12.jpg",
    images: [
      "/images/work/logo/hdl/work1.jpg",
      "/images/work/logo/hdl/work2.jpg",
      "/images/work/logo/hdl/work3.jpg",
      "/images/work/logo/hdl/work4.jpg",
      "/images/work/logo/hdl/work5.jpg",
      "/images/work/logo/hdl/work6.jpg",
      "/images/work/logo/hdl/work7.jpg"
            ],
    description: {
      ru: "Логотип, созданный для киберспортивной команды Hope Dies Last. В его основе — образ воина, сражающегося до последнего дыхания. Когда единственным остаётся лишь надежда, вспыхивает искра, воплощённая в виде огня, исходящего из левого глаза.",
      en: "A logo created for the esports team Hope Dies Last. It is based on the image of a warrior fighting until his last breath. When hope is all that remains, a spark flares up, represented by the fire emanating from his left eye.",
      ro: "Logo-ul creat pentru echipa de e-sport Hope Dies Last. La baza acestuia stă imaginea unui războinic care luptă până la ultima suflare. Când nu mai rămâne decât speranța, se aprinde o scânteie, reprezentată sub forma unui foc care izvorăște din ochiul stâng.",
    },
  },
];

export function getProjectBySlug(slug: string) {
  return projects.find((p) => p.slug === slug);
}
