import { Project } from "@/types/project";

// Плейсхолдеры — замени cover/images на свои работы (см. /public/images/work),
// заполни title/description на трёх языках. slug используется в адресе
// страницы проекта: /work/<slug> — сделай его коротким и на латинице.
export const projects: Project[] = [
  {
    id: "1",
    slug: "socurdmitrii_logo",
    title: { ru: "Логотип для дизайнера Socur Dmitrii",
            en: "Logo for designer Socur Dmitrii",
            ro: "Logo pentru designerul Socur Dmitrii" },
    categoryKey: "branding",

    year: 2026,
    cover: "/images/work/logo/socurdmitrii/cover-1.jpg",
    images: [
      "/images/work/logo/socurdmitrii/work.jpg",
      "/images/work/logo/socurdmitrii/work3.png",
      "/images/work/logo/socurdmitrii/work4.png",
      "/images/work/logo/socurdmitrii/work5.jpg",
      "/images/work/logo/socurdmitrii/work6.jpg",
      "/images/work/logo/socurdmitrii/work8.png",
      "/images/work/logo/socurdmitrii/work7.jpg",
      "/images/work/logo/socurdmitrii/work9.jpg"],
    description: {
      ru: "Логотип, разработанный для себя. Лого выполнено в плоском стиле, сочетает в себе аббревиатуру имени и фамилии Socur Dmitrii. Помимо этого, для формирования визуального баланса левая часть была дополнена вертикальным элементом, который замыкает фигуру.",
      en: "A logo I designed for myself. The logo is created in a flat style and combines the initials of my first and last name, Socur Dmitrii. In addition, to create visual balance, a vertical element was added to the left side to complete the shape.",
      ro: "Un logo creat pentru mine. Logo-ul este realizat în stil plat și combină inițialele numelui și prenumelui Socur Dmitrii. În plus, pentru a crea un echilibru vizual, partea stângă a fost completată cu un element vertical care încheie forma.",
    },
  },
  {
    id: "2",
    slug: "energywind_prezentation",
    title: { ru: "Презентация компании System Global Group в области ветроэнергетики (Energy Wind Moldova)",
            en: "System Global Group's Presentation on Wind Energy (Energy Wind Moldova)",
            ro: "Prezentarea companiei System Global Group în domeniul energiei eoliene (Energy Wind Moldova)" },
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/energy_prezentation/cover-2.jpg",
    images: [
  "/images/work/web/energy_prezentation/лист 1 копия.jpg",
  "/images/work/web/energy_prezentation/лист 2 копия.jpg",
  "/images/work/web/energy_prezentation/лист 3 копия.jpg",
  "/images/work/web/energy_prezentation/лист 4 копия.jpg",
  "/images/work/web/energy_prezentation/лист 5 копия.jpg",
  "/images/work/web/energy_prezentation/лист 6 копия.jpg",
  "/images/work/web/energy_prezentation/лист 7 копия.jpg",
  "/images/work/web/energy_prezentation/лист 8 копия.jpg",
  "/images/work/web/energy_prezentation/лист 9 копия.jpg",
  "/images/work/web/energy_prezentation/лист 10 копия.jpg",
  "/images/work/web/energy_prezentation/лист 11 копия.jpg",
  "/images/work/web/energy_prezentation/лист 12 копия.jpg",
  "/images/work/web/energy_prezentation/лист 13 копия.jpg",
  "/images/work/web/energy_prezentation/лист 14 копия.jpg",
  "/images/work/web/energy_prezentation/лист 15 копия.jpg",
  "/images/work/web/energy_prezentation/лист 16 копия.jpg",
  "/images/work/web/energy_prezentation/лист 17 копия.jpg",
  "/images/work/web/energy_prezentation/лист 18 копия.jpg",
  "/images/work/web/energy_prezentation/лист 19 копия.jpg",
  "/images/work/web/energy_prezentation/лист 20 копия.jpg"
],

    description: {
      ru: "Презентация для компании Energy Wind Moldova в области ветроэнергетики показывает, чем занимается клиент: строительство ветряных электростанций и систем накопления энергии, их монтаж, сервисное обслуживание и финансирование проектов. В документе отражены ключевые направления — надёжность оборудования, технологическая экспертиза, доступные финансовые инструменты (лизинг, рассрочка), а также вклад компании в устойчивое развитие и экологичность решений.",
      en: "This presentation for Energy Wind Moldova, a company in the wind energy sector, outlines the client’s core activities: the construction of wind power plants and energy storage systems, their installation, maintenance, and project financing. The document highlights key areas—equipment reliability, technical expertise, accessible financial instruments (leasing, installment plans), as well as the company’s contribution to sustainable development and environmentally friendly solutions.",
      ro: "Prezentarea pentru compania Energy Wind Moldova din domeniul energiei eoliene ilustrează activitatea clientului: construcția de centrale eoliene și sisteme de stocare a energiei, instalarea acestora, întreținerea și finanțarea proiectelor. Documentul evidențiază direcțiile cheie — fiabilitatea echipamentelor, expertiza tehnologică, instrumentele financiare accesibile (leasing, rate), precum și contribuția companiei la dezvoltarea durabilă și la caracterul ecologic al soluțiilor.",
    },
  },
  {
    id: "3",
    slug: "project-three",
    title: { ru: "Название проекта", en: "Project name", ro: "Numele proiectului" },
    categoryKey: "print",
    year: 2025,
    cover: "/images/work/cover-3.svg",
    images: ["/images/work/cover-3.svg", "/images/work/detail-1.svg", "/images/work/detail-2.svg"],
    description: {
      ru: "Краткое описание проекта: расскажи, что сделал в этой работе. Замени этот текст на реальную историю.",
      en: "Short project description: tell the story of what you did in this piece of work. Replace this with the real text.",
      ro: "Descriere scurtă a proiectului: povestește ce ai făcut în acest proiect. Înlocuiește cu textul real.",
    },
  },
  {
    id: "4",
    slug: "persistentmma_steclo",
    title: { ru: "Оракал на стекло для додзё Persistent MMA в городе Кишинёв", en: "Oracle on glass for Persistent MMA dojo in Chișinău", ro: "Oracle pe sticlă pentru dojosul Persistent MMA în Chișinău" },
    categoryKey: "packaging",
    year: 2026,
    cover: "/images/work/web/mma_steclo/cover-4.jpg",
    images: ["/images/work/web/mma_steclo/1.jpg",
            "/images/work/web/mma_steclo/2.jpg",],

    description: {
      ru: "Проект, выполненный для додзё Persistent MMA в городе Кишинёв. На стекло нанесён оракал с логотипом клуба и 14 величайшими бойцами MMA (по мнению клиента). Данный проект реализован в рамках сотрудничества с клубом, чтобы улучшить визуальное представление и идентичность додзё.",
      en: "A project completed for the Persistent MMA dojo in Chisinau. An oracle featuring the club's logo and 14 of the greatest MMA fighters (according to the client) was applied to the glass. This project was implemented as part of a collaboration with the club to enhance the dojo's visual identity.",
      ro: "Un proiect finalizat pentru dojo-ul Persistent MMA din Chișinău. Pe sticlă a fost aplicat un oracol cu ​​logo-ul clubului și 14 dintre cei mai mari luptători MMA (conform clientului). Acest proiect a fost implementat ca parte a unei colaborări cu clubul pentru a îmbunătăți identitatea vizuală a dojo-ului.",
    },
  },
  {
    id: "5",
    slug: "sport_spirit_1",
    title: { ru: "Рекламный креатив для коллекции одежды Converse, Sport Spirit", en: "Advertising creative for Converse Sport Spirit collection", ro: "Creativ publicitar pentru colecția Converse Sport Spirit" },
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/ss_1/cover-5.jpg",
    images: ["/images/work/web/ss_1/1.jpg",
              "/images/work/web/ss_1/2.jpg",
              "/images/work/web/ss_1/3.jpg"],
    description: {
      ru: "Рекламный креатив для коллекции одежды Converse, Sport Spirit. В рамках проекта была разработана концепция, создан визуальный контент и реализована рекламная кампания в социальных сетях.",
      en: "Advertising creative for Converse Sport Spirit collection. As part of the project, a concept was developed, visual content was created, and a social media advertising campaign was implemented.",
      ro: "Creativ publicitar pentru colecția Converse Sport Spirit. În cadrul proiectului, a fost dezvoltată o concept, a fost creat conținut vizual și a fost implementată o campanie de publicitate în rețelele sociale.",
    },
  },
  {
    id: "6",
    slug: "sport_spirit_2",
    title: { ru: "Рекламный креатив для сезонной акции Black Friday, PUMA Moldova", en: "Advertising creative for the Black Friday seasonal promotion, PUMA Moldova", ro: "Concept publicitar pentru campania sezonieră de Black Friday, PUMA Moldova" },
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/ss_2/cover-6.jpg",
    images: ["/images/work/web/ss_2/1.jpg",
              "/images/work/web/ss_2/2.jpg",
              "/images/work/web/ss_2/3.jpg"],
    description: {
      ru: "Рекламный креатив для сезонной акции Black Friday, PUMA Moldova. В рамках проекта была разработана концепция, создан визуальный контент и реализована рекламная кампания для продвижения в социальных сетях.",
      en: "Advertising creative for the Black Friday seasonal promotion, PUMA Moldova. As part of the project, a concept was developed, visual content was created, and an advertising campaign was launched for promotion on social media.",
      ro: "Concept publicitar pentru campania sezonieră de Black Friday, PUMA Moldova. În cadrul proiectului, s-a elaborat conceptul, s-a creat conținutul vizual și s-a derulat campania publicitară pentru promovarea pe rețelele sociale.",
    },
  },
  {
    id: "14",
    slug: "project-14",
    title: { ru: "Название проекта", en: "Project name", ro: "Numele proiectului" },
    categoryKey: "Motion design",
    year: 2024,
    cover: "/images/work/cover-6.svg",
    images: ["/images/work/cover-6.svg", "/images/work/detail-1.svg", "/images/work/detail-2.svg"],
    description: {
      ru: "Логотип созданный в рамках лицензионного проекта (Исследование и разработка визуальной идентичности Факультета ȘREM, USARB: от концепции до реализации), с последующем применением. В основе логотипа лежит аббревиатура слов Matematica/Informatica, вписанные в увадратные скобки, которые используются в обеих дисциплинах.",
      en: "Short project description: tell the story of what you did in this piece of work. Replace this with the real text.",
      ro: "Descriere scurtă a proiectului: povestește ce ai făcut în acest proiect. Înlocuiește cu textul real.",
    },
  },
  {
    id: "7",
    slug: "catedra_matinf_logo",
    title: { ru: "Логотип для кафедры математики и информатики факультета ȘREM, USARB", en: "Logo for the Department of Mathematics and Computer Science, ȘREM Faculty, USARB", ro: "Logotip pentru catedra de matematică și informatică a facultății ȘREM, USARB" },
    categoryKey: "branding",
    year: 2026,
    cover: "/images/work/logo/matematica/cover-7.jpg",
    images: [
      "/images/work/logo/matematica/work1.jpg",
      "/images/work/logo/matematica/work2.jpg",
      "/images/work/logo/matematica/work3.png",
      "/images/work/logo/matematica/work4.jpg",
      "/images/work/logo/matematica/work5.jpg",
      "/images/work/logo/matematica/work6.jpg",
      "/images/work/logo/matematica/work7.jpg",
      "/images/work/logo/matematica/work8.jpg"
            ],
    description: {
      ru: "Логотип, созданный в рамках лицензионного проекта («Исследование и разработка визуальной идентичности факультета ȘREM, USARB: от концепции до реализации»), с последующим применением. В основе логотипа лежит аббревиатура слов Matematica/Informatica, вписанных в квадратные скобки, которые используются в обеих дисциплинах.",
      en: "A logo created as part of a licensing project (“Research and Development of the Visual Identity for the ȘREM Faculty, USARB: From Concept to Implementation”), followed by its implementation. The logo is based on the abbreviation of the words “Matematica/Informatica,” enclosed in square brackets, which are used in both disciplines.",
      ro: "Logo-ul creat în cadrul proiectului licențial („Cercetarea și dezvoltarea identității vizuale a Facultății ȘREM, USARB: de la concept la realizare”), urmat de punerea sa în practică. La baza logo-ului stă abrevierea cuvintelor „Matematica/Informatica”, încadrate între paranteze pătrate, care sunt utilizate în ambele discipline.",
    },
  },
  {
    id: "8",
    slug: "sport_spirit_3",
    title: { ru: "Рекламный креатив для коллекции одежды Nike, Sport Spirit", en: "Advertising campaign for the Nike “Sport Spirit” clothing collection", ro: "Conceptul publicitar pentru colecția de îmbrăcăminte Nike, „Sport Spirit”" },
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/ss_3/cover-8.jpg",
    images: ["/images/work/web/ss_3/1.jpg",
            "/images/work/web/ss_3/2.jpg",
            "/images/work/web/ss_3/3.jpg"],
    description: {
      ru: "Рекламный креатив для коллекции одежды Nike, Sport Spirit. В рамках проекта была разработана концепция, создан визуальный контент и реализована рекламная кампания в социальных сетях.",
      en: "Advertising campaign for the Nike “Sport Spirit” clothing collection. As part of the project, a concept was developed, visual content was created, and an advertising campaign was implemented on social media.",
      ro: "Concept publicitar pentru colecția de îmbrăcăminte Nike, „Sport Spirit”. În cadrul proiectului a fost dezvoltată o concept, creat conținut vizual și implementată o campanie publicitară pe rețelele sociale.",
    },
  },
  {
    id: "9",
    slug: "project-nine",
    title: { ru: "Название проекта", en: "Project name", ro: "Numele proiectului" },
    categoryKey: "print",
    year: 2023,
    cover: "/images/work/cover-9.svg",
    images: ["/images/work/cover-9.svg", "/images/work/detail-1.svg", "/images/work/detail-2.svg"],
    description: {
      ru: "Краткое описание проекта: расскажи, что сделал в этой работе. Замени этот текст на реальную историю.",
      en: "Short project description: tell the story of what you did in this piece of work. Replace this with the real text.",
      ro: "Descriere scurtă a proiectului: povestește ce ai făcut în acest proiect. Înlocuiește cu textul real.",
    },
  },
  {
    id: "10",
    slug: "project-ten",
    title: { ru: "Название проекта", en: "Project name", ro: "Numele proiectului" },
    categoryKey: "print",
    year: 2023,
    cover: "/images/work/cover-10.svg",
    images: ["/images/work/cover-10.svg", "/images/work/detail-1.svg", "/images/work/detail-2.svg"],
    description: {
      ru: "Краткое описание проекта: расскажи, что сделал в этой работе. Замени этот текст на реальную историю.",
      en: "Short project description: tell the story of what you did in this piece of work. Replace this with the real text.",
      ro: "Descriere scurtă a proiectului: povestește ce ai făcut în acest proiect. Înlocuiește cu textul real.",
    },
  },
  {
    id: "11",
    slug: "energywind_logo",
    title: { ru: "Логотип для компании в области ветроэнергетики System Global Group (Energy Wind Moldova)",
            en: "Logo for System Global Group (Energy Wind Moldova), a company in the wind energy sector",
            ro: "Logo pentru compania din domeniul energiei eoliene System Global Group (Energy Wind Moldova)" },
    categoryKey: "branding",
    year: 2026,
    cover: "/images/work/logo/energywind/cover-11.jpg",
    images: [
      "/images/work/logo/energywind/work1.jpg",
      "/images/work/logo/energywind/work2.jpg",
      "/images/work/logo/energywind/work3.jpg",
      "/images/work/logo/energywind/work4.jpg",
      "/images/work/logo/energywind/work5.jpg",
      "/images/work/logo/energywind/work6.jpg",
      "/images/work/logo/energywind/work9.jpg",
      "/images/work/logo/energywind/work7.jpg",
      "/images/work/logo/energywind/work8.jpg"
            ],
    description: {
      ru: "Логотип, созданный для компании, которая занимается ветроэнергетикой в Молдове — Energy Wind Moldova. Логотип выполнен в современном стиле с использованием зелёных оттенков, отражающих экологичность и возобновляемую энергию.",
      en: "A logo created for a company specializing in wind energy in Moldova — Energy Wind Moldova. The logo is designed in a modern style using green shades that reflect environmental friendliness and renewable energy.",
      ro: "Logo-ul creat pentru o companie care se ocupă de energie eoliană în Moldova — Energy Wind Moldova. Logo-ul este realizat într-un stil modern folosind nuanțe de verde care reflectă prietenia față de mediu și energia regenerabilă.",
    },
  },
  {
    id: "12",
    slug: "HDL_logo",
    title: { ru: "Логотип для киберспортивной команды HDL (Hope Dies Last)",
            en: "Logo for the HDL (Hope Dies Last) esports team",
            ro: "Logo pentru echipa de e-sport HDL (Hope Dies Last)" },
    categoryKey: "branding",
    year: 2026,
    cover: "/images/work/logo/hdl/cover-12.jpg",
    images: [
      "/images/work/logo/hdl/work1.jpg",
      "/images/work/logo/hdl/work2.jpg",
      "/images/work/logo/hdl/work3.jpg",
      "/images/work/logo/hdl/work4.jpg",
      "/images/work/logo/hdl/work5.jpg",
      "/images/work/logo/hdl/work6.jpg",
      "/images/work/logo/hdl/work7.jpg"
            ],
    description: {
      ru: "Логотип, созданный для киберспортивной команды Hope Dies Last. В его основе — образ воина, сражающегося до последнего дыхания. Когда единственным остаётся лишь надежда, вспыхивает искра, воплощённая в виде огня, исходящего из левого глаза.",
      en: "A logo created for the esports team Hope Dies Last. It is based on the image of a warrior fighting until his last breath. When hope is all that remains, a spark flares up, represented by the fire emanating from his left eye.",
      ro: "Logo-ul creat pentru echipa de e-sport Hope Dies Last. La baza acestuia stă imaginea unui războinic care luptă până la ultima suflare. Când nu mai rămâne decât speranța, se aprinde o scânteie, reprezentată sub forma unui foc care izvorăște din ochiul stâng.",
    },
  },
  {
    id: "13",
    slug: "project-13",
    title: { ru: "Название проекта", en: "Project name", ro: "Numele proiectului" },
    categoryKey: "video-editing",
    year: 2025,
    cover: "/images/work/cover-5.svg",
    images: ["/images/work/cover-5.svg", "/images/work/detail-1.svg", "/images/work/detail-2.svg"],
    description: {
      ru: "Краткое описание проекта: расскажи, что сделал в этой работе. Замени этот текст на реальную историю.",
      en: "Short project description: tell the story of what you did in this piece of work. Replace this with the real text.",
      ro: "Descriere scurtă a proiectului: povestește ce ai făcut în acest proiect. Înlocuiește cu textul real.",
    },
  },
  {
    id: "15",
    slug: "sport_spirit_4",
    title: { ru: "Рекламный креатив для акции -30% extra sale Black Friday, Sport Spirit",
              en: "Advertising creative for the “-30% Extra Black Friday Sale” promotion, Sport Spirit",
              ro: "Conceptul publicitar pentru promoția „-30% extra sale Black Friday”, Sport Spirit"},
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/ss_4/cover-15.jpg",
    images: ["/images/work/web/ss_4/1.jpg",
            "/images/work/web/ss_4/2.jpg",
            "/images/work/web/ss_4/3.jpg"],
    description: {
      ru: "Рекламный креатив для акции -30% extra sale Black Friday, Sport Spirit. В рамках проекта была разработана концепция, создан визуальный контент и реализована рекламная кампания в социальных сетях.",
      en: "Advertising creative for the “-30% Extra Black Friday Sale” promotion, Sport Spirit. As part of the project, a concept was developed, visual content was created, and an advertising campaign was implemented on social media.",
      ro: "Concept publicitar pentru promoția „-30% extra sale Black Friday”, Sport Spirit. În cadrul proiectului a fost dezvoltată o concept, creat conținut vizual și implementată o campanie publicitară pe rețelele sociale.",
    },
  },
  {
    id: "16",
    slug: "sport_spirit_5",
    title: { ru: "Рекламный креатив для продукции Crep Protect, Sport Spirit",
              en: "Advertising concepts for Crep Protect and Sport Spirit products",
              ro: "Concepte publicitare pentru produsele Crep Protect și Sport Spirit"},
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/ss_5/cover-16.jpg",
    images: ["/images/work/web/ss_5/1.jpg",
            "/images/work/web/ss_5/2.jpg",
            "/images/work/web/ss_5/3.jpg"],
    description: {
      ru: "Рекламный креатив для продукции Crep Protect, Sport Spirit. В рамках проекта была разработана концепция, создан визуальный контент и реализована рекламная кампания в социальных сетях.",
      en: "Advertising creative for Crep Protect and Sport Spirit products. As part of the project, a concept was developed, visual content was created, and an advertising campaign was launched on social media.",
      ro: "Concept publicitar pentru produsele Crep Protect și Sport Spirit. În cadrul proiectului a fost dezvoltată o concept, creat conținut vizual și implementată o campanie publicitară pe rețelele sociale.",
    },
  },
   {
    id: "17",
    slug: "sport_spirit_6",
    title: { ru: "Рекламный креатив для акции -70% Mega Sale, Sport Spirit",
              en: "Advertising creative for the “-70% Mega Sale” promotion, Sport Spirit",
              ro: "Conceptul publicitar pentru promoția „-70% Mega Sale”, Sport Spirit"},
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/ss_6/cover-17.jpg",
    images: ["/images/work/web/ss_6/1.jpg",
            "/images/work/web/ss_6/2.jpg",],
    description: {
      ru: "Рекламный креатив для продукции Sport Spirit Outlet. В рамках проекта была разработана концепция визуальной кампании, создан графический контент с акцентом на скидки до 70%. Итоговый материал был реализован в социальных сетях и использован для продвижения масштабной распродажи.",
      en: "Advertising creative for Sport Spirit Outlet products. As part of the project, a concept for a visual campaign was developed, and graphic content was created highlighting discounts of up to 70%. The final materials were published on social media and used to promote a large-scale sale.",
      ro: "Concepție publicitară pentru produsele Sport Spirit Outlet. În cadrul proiectului, a fost elaborată conceptul campaniei vizuale și a fost creat conținut grafic care pune accentul pe reduceri de până la 70%. Materialul final a fost publicat pe rețelele sociale și utilizat pentru promovarea unei vânzări la scară largă.",
    },
  },
  {
    id: "18",
    slug: "sport_spirit_7",
    title: { ru: "Рекламный креатив для зимней коллекции одежды Adidas, Sport Spirit",
              en: "Advertising campaign for the Adidas winter clothing collection, “Sport Spirit”",
              ro: "Conceptul publicitar pentru colecția de iarnă de îmbrăcăminte Adidas, Sport Spirit"},
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/ss_7/cover-18.jpg",
    images: ["/images/work/web/ss_7/1.jpg",
            "/images/work/web/ss_7/2.jpg",
            "/images/work/web/ss_7/3.jpg",],
    description: {
      ru: "Рекламный креатив для продукции Adidas, Sport Spirit. В рамках проекта была разработана концепция зимней кампании, создан визуальный контент с акцентом на стиль и комфорт в холодный сезон. Итоговый материал был реализован в социальных сетях и использован для продвижения коллекции зимней одежды.",
      en: "Advertising creative for Adidas and Sport Spirit products. As part of the project, a concept for a winter campaign was developed, and visual content was created with an emphasis on style and comfort during the cold season. The final material was published on social media and used to promote the winter clothing collection.",
      ro: "Concepție publicitară pentru produsele Adidas, Sport Spirit. În cadrul proiectului, a fost elaborată o concepție pentru campania de iarnă și a fost creat conținut vizual care pune accentul pe stil și confort în sezonul rece. Materialul final a fost publicat pe rețelele sociale și utilizat pentru promovarea colecției de îmbrăcăminte de iarnă.",
    },
  },
  {
    id: "19",
    slug: "sport_spirit_8",
    title: { ru: "Рекламный креатив для коллекции лёгкой одежды Adidas, Sport Spirit",
              en: "Advertising campaign for the Adidas light clothing collection, “Sport Spirit”",
              ro: "Conceptul publicitar pentru colecția de îmbrăcăminte ușoară Adidas, Sport Spirit"},
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/ss_8/cover-19.jpg",
    images: ["/images/work/web/ss_8/1.jpg",
            "/images/work/web/ss_8/2.jpg",
            "/images/work/web/ss_8/3.jpg",],
    description: {
      ru: "Рекламный креатив для легкой одежды Adidas, Sport Spirit. В рамках проекта была разработана концепция кампании легкой одежды, создан визуальный контент с акцентом на стиль и комфорт в теплый период. Итоговый материал был реализован в социальных сетях и использован для продвижения.",
      en: "Advertising creative for Adidas’s lightweight apparel line, Sport Spirit. As part of the project, a campaign concept for lightweight apparel was developed, and visual content was created with an emphasis on style and comfort during the warmer months. The final content was published on social media and used for promotional purposes.",
      ro: "Conceptul publicitar pentru colecția de îmbrăcăminte ușoară Adidas, „Sport Spirit”. În cadrul proiectului, a fost elaborat conceptul campaniei pentru colecția de îmbrăcăminte ușoară și a fost creat conținut vizual care pune accentul pe stil și confort în perioada caldă. Materialul final a fost publicat pe rețelele sociale și utilizat în scopuri de promovare.",
    },
  },
  {
    id: "20",
    slug: "sport_spirit_9",
    title: { ru: "Рекламный креатив для коллекции одежды Adidas, Sport Spirit",
              en: "Advertising campaign for the Adidas “Sport Spirit” clothing collection",
              ro: "Conceptul publicitar pentru colecția de îmbrăcăminte Adidas, Sport Spirit"},
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/ss_9/cover-20.jpg",
    images: ["/images/work/web/ss_9/1.jpg",
            "/images/work/web/ss_9/2.jpg",
            "/images/work/web/ss_9/3.jpg",],
    description: {
      ru: "Рекламный креатив для одежды Adidas, Sport Spirit. В рамках проекта была разработана концепция кампании, создан визуальный контент и реализована рекламная кампания в социальных сетях.",
      en: "Advertising creative for Adidas apparel, “Sport Spirit.” As part of the project, a campaign concept was developed, visual content was created, and an advertising campaign was launched on social media.",
      ro: "Concepție publicitară pentru colecția de îmbrăcăminte Adidas, „Sport Spirit”. În cadrul proiectului, s-a elaborat conceptul campaniei, s-a creat conținutul vizual și s-a derulat campania publicitară pe rețelele sociale.",
    },
  },
  {
    id: "21",
    slug: "sport_spirit_10",
    title: { ru: "Рекламный креатив для коллекции школьной атрибутики Back to School: рюкзаки от Sport Spirit",
              en: "Advertising campaign for the “Back to School” collection of school supplies: backpacks from Sport Spirit",
              ro: "Conceptul publicitar pentru colecția de articole școlare „Back to School”: rucsacuri de la Sport Spirit"},
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/ss_10/cover-21.jpg",
    images: ["/images/work/web/ss_10/1.png",
            "/images/work/web/ss_10/2.png",
            "/images/work/web/ss_10/3.png",],
    description: {
      ru: "Рекламный креатив для продукции Adidas и Puma, Sport Spirit в рамках кампании Back to School. Проект был ориентирован на начало сентября: разработана концепция, создан визуальный контент с акцентом на доступные цены и стильные рюкзаки для учебного сезона. Итоговый материал использован в социальных сетях и промо‑акциях для привлечения студентов и школьников к бренду.",
      en: "Advertising creative for Adidas and Puma products, Sport Spirit, as part of the Back to School campaign. The project was timed for early September: a concept was developed, and visual content was created with an emphasis on affordable prices and stylish backpacks for the school year. The final materials were used on social media and in promotional campaigns to attract students and schoolchildren to the brand.",
      ro: "Concepție publicitară pentru produsele Adidas și Puma, Sport Spirit, în cadrul campaniei „Back to School”. Proiectul a fost orientat către începutul lunii septembrie: s-a elaborat conceptul și s-a creat conținutul vizual, punând accentul pe prețurile accesibile și rucsacurile elegante pentru noul an școlar. Materialul final a fost utilizat pe rețelele sociale și în campaniile promoționale pentru a atrage studenții și elevii către brand.",
    },
  },
  {
    id: "22",
    slug: "sport_spirit_11",
    title: { ru: "Рекламный креатив для коллекции обуви Adidas, Sport Spirit",
              en: "Advertising campaign for the new collection of shoes from Sport Spirit",
              ro: "Conceptul publicitar pentru noua colecție de încălțăminte de la Sport Spirit"},
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/ss_11/cover-22.jpg",
    images: ["/images/work/web/ss_11/1.png",
            "/images/work/web/ss_11/2.png",
            "/images/work/web/ss_11/3.png",],
    description: {
      ru: "Рекламный креатив для продукции Adidas, Sport Spirit, посвящён запуску новой коллекции. В рамках проекта была разработана концепция с акцентом на спортивный стиль и динамику движения: визуальный контент построен вокруг фирменных элементов бренда — контрастных полос, текстуры беговой дорожки и актуальной модели кроссовок. Кампания была реализована в социальных сетях и использована для продвижения свежей линейки обуви, подчеркивая её современность и связь с активным образом жизни.",
      en: "This advertising campaign for Adidas’ Sport Spirit line is dedicated to the launch of a new collection. As part of the project, a concept was developed that emphasizes athletic style and the dynamics of movement: the visual content is built around the brand’s signature elements—contrasting stripes, the texture of a running track, and a current sneaker model. The campaign was rolled out on social media and used to promote the new line of shoes, highlighting its modernity and connection to an active lifestyle.",
      ro: "Campania publicitară pentru produsele Adidas, Sport Spirit, este dedicată lansării noii colecții. În cadrul proiectului a fost elaborată o concepție care pune accentul pe stilul sportiv și dinamica mișcării: conținutul vizual este construit în jurul elementelor caracteristice ale mărcii — dungile contrastante, textura pistei de alergare și modelul actual de adidași. Campania a fost derulată pe rețelele sociale și utilizată pentru promovarea noii linii de încălțăminte, subliniind caracterul său modern și legătura cu un stil de viață activ.",
    },
  },
  {
    id: "23",
    slug: "sport_spirit_12",
    title: { ru: "Рекламный креатив для коллекции спортивной обуви Adidas, Sport Spirit",
              en: "Advertising campaign for the new collection of athletic shoes from Sport Spirit",
              ro: "Conceptul publicitar pentru noua colecție de încălțăminte sportivă de la Sport Spirit"},
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/ss_12/cover-23.jpg",
    images: ["/images/work/web/ss_12/1.png",
            "/images/work/web/ss_12/2.png",
            "/images/work/web/ss_12/3.png",],
    description: {
      ru: "Рекламный креатив для продукции Adidas, Sport Spirit. В рамках проекта была разработана концепция запуска новой коллекции спортивной обуви, создан визуальный контент с акцентом на современный дизайн и технологичность модели. Центральным элементом стал кроссовок в черно‑зелёной гамме на подиуме, подчёркивающий инновацию и стиль бренда. Кампания была реализована в социальных сетях и использована для продвижения эксклюзивной линейки в магазине Sport Spirit.",
      en: "Advertising creative for Adidas and Sport Spirit products. As part of the project, a concept was developed for the launch of a new collection of athletic shoes, and visual content was created with an emphasis on the models’ modern design and technological features. The central element was a pair of sneakers in a black-and-green color scheme displayed on a podium, highlighting the brand’s innovation and style. The campaign was rolled out on social media and used to promote an exclusive line at the Sport Spirit store.",
      ro: "Concept publicitar pentru produsele Adidas, Sport Spirit. În cadrul proiectului, a fost elaborată o strategie de lansare a noii colecții de încălțăminte sportivă și a fost creat conținut vizual care pune accentul pe designul modern și caracterul tehnologic al modelului. Elementul central a fost o pereche de adidași în nuanțe de negru și verde, așezați pe o podium, care subliniază inovația și stilul mărcii. Campania a fost derulată pe rețelele sociale și utilizată pentru promovarea liniei exclusive în magazinul Sport Spirit.",
    },
  },
  {
    id: "24",
    slug: "sport_spirit_13",
    title: { ru: "Рекламный креатив для новой коллекции Nike, Jordan и Yankees, Sport Spirit",
              en: "Advertising campaign for the new Nike, Jordan, and Yankees collection, Sport Spirit",
              ro: "Conceptul publicitar pentru noua colecție Nike, Jordan și Yankees, Sport Spirit"},
    categoryKey: "web",
    year: 2025,
    cover: "/images/work/web/ss_13/cover-24.jpg",
    images: ["/images/work/web/ss_13/1.jpg",
            "/images/work/web/ss_13/2.jpg",
            "/images/work/web/ss_13/3.jpg",],
    description: {
      ru: "Рекламный креатив, разработанный для магазина Sport Spirit с целью продвижения зимней коллекции одежды и аксессуаров Nike, Jordan и New York Yankees. Основной акцент сделан на выразительной типографике, контрастной цветовой гамме и современном визуальном стиле, который эффективно привлекает внимание аудитории в социальных сетях.",
      en: "Advertising creative developed for the Sport Spirit store to promote the winter collection of Nike, Jordan, and New York Yankees apparel and accessories. The focus is on striking typography, a contrasting color palette, and a modern visual style that effectively captures the audience’s attention on social media.",
      ro: "Conceptul publicitar creat pentru magazinul Sport Spirit, cu scopul de a promova colecția de iarnă de îmbrăcăminte și accesorii Nike, Jordan și New York Yankees. Accentul principal este pus pe tipografia expresivă, pe paleta de culori contrastante și pe stilul vizual modern, care atrage în mod eficient atenția publicului pe rețelele sociale.",
    },
  },
];

export function getProjectBySlug(slug: string) {
  return projects.find((p) => p.slug === slug);
}
